deployment:
    tasks:
        - export DEPLOYPATH=[path]
        - /usr/local/bin/composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
        - /bin/cp -r web/* $DEPLOYPATH